### ISSUE TITLE
Compile error while building package

### ISSUE THREAD

**Issue by ravijha65** [w-wallner/libPTP#1]
HI , Wallner,
Thanks for ur work its really seems amazing, here i tried to build your package but i got some compilation error.
Omnet 4.6
Inet 2.6
Ubuntu Linux

Error details as below:

src/Software/SimTimeFilter/MovingAvg/MovingAvgSimTimeFilter.cc:29:37: fatal error: boost/circular_buffer.hpp: No such file or directory
# include <boost/circular_buffer.hpp>

```
                                 ^
```

compilation terminated.
make: **\* [out/gcc-debug//src/Software/SimTimeFilter/MovingAvg/MovingAvgSimTimeFilter.o] Error 1

20:29:13 Build Finished (took 1m:37s.692ms)

Please help to fix this.. Thanks in advance

**Comment by w-wallner** [comment]
Hi,

you need to install the Boost C++ library.
On my system (Ubuntu 16.10) it is the package libboost1.58-dev

regards, Wolfgang
