### ISSUE TITLE
boost reference with ptplib

### ISSUE THREAD

**Issue by alukkas** [w-wallner/libPTP#2]
Hi
I like the way you have designed the nodes for clocks Mr. Wallner. I am going to use your project and simulate a network for research purposes of PTP. 
I am getting the following errors even though I am using the supported version of omnet++ and inet. Please let me know of any suggestions. It would be appreciable. 

![screen shot 2017-07-18 at 2 28 13 pm](https://user-images.githubusercontent.com/29707084/28333335-a7f862ce-6bc5-11e7-8e21-f58bdaaade2c.png)

**Comment by dee101k** [comment]
Hello alukkas,

I also want to do the same for my Master Thesis project. However, I am facing difficulty in installing OMNET++ 4.6 on Windows 10. I have following problem.
![aa](https://user-images.githubusercontent.com/7173728/64339979-6a561e80-cfe5-11e9-8e9a-438a8efa7067.PNG)

Do you also encountered with similar problem while installing on Windows 10? Please let me know if you know anything as how to solve the problem.
