### ISSUE TITLE
Unable to install OMNET++ 4.6 on WIndows 10

### ISSUE THREAD

**Issue by dee101k** [w-wallner/libPTP#4]
I want to use OMNET++ for running libPTP repository. It uses the 4.6 version, but I am not able to install this version using ./configure option. However, with similar steps can install latest version 5.5. Following is the problem which I am getting.

Installation problem
![aa](https://user-images.githubusercontent.com/7173728/64343611-20713680-cfed-11e9-8dc7-9b653ae7bc33.PNG)

Please let me know if anyone else experienced a similar problem?

**Comment by w-wallner** [comment]
Sorry, we can't provide OMNeT++ support.
For OMNeT++ I recommend using a virtual machine with an older OS.
Especially Ubuntu 16.04 is known to work very well with OMNeT++ 4.6.
